### ISSUE TITLE
NAs in water measurements

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwgtools#24]
As reported by @nacmarino , @dsrivast : 

both the cv.depth as well as the wetness for argentina_15 are missing. This shouldn't be so, as there is a mean and a maximum value on the spreadsheet.

And time.since.minimum is entirely NA...all bromelaids all sites.

argentina_15 is not NA but NaN, suggesting that there is illegal math
issue.

**Comment by aammd** [comment]
This is possibly related to @DEZERALDOlivier 's observations of problems in #22 and #23

**Comment by nacmarino** [comment]
There is still a problem with the calculations of hydro variables.

I haven't went through the original data, but problems are:
1 - Argentina data set: NaN for one bromeliad both for cv.depth and wetness. Could it be a problem with very few observations and/or presence of NA's? I believe we should include the argument na.rm = TRUE, whatever we call function mean.

2 - All data sets: times.since.minimum is NA. I believe this is the problem raised by @DEZERALDOlivier.

**Comment by aammd** [comment]
We can definitely get this solved, but it will probably have to be a project for Rio. Let's work on it together there!

**Comment by aammd** [comment]
The Curious Case of Bromeliad 15 is resolved, by either 

* living with the NA (at the level of the leaf)
* averaging it away (with `na.rm = TRUE`) ; this leaves you with a **HUGE** value
* replacing it with `argentina_24`, a la Regis
